/*
 * JSP generated by Resin Professional 4.0.13 (built Tue, 09 Nov 2010 03:50:16 PST)
 */

package _jsp._web_22dinf._jsp._organization;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;

public class _maintain__jsp extends com.caucho.jsp.JavaPage
{
  private static final java.util.HashMap<String,java.lang.reflect.Method> _jsp_functionMap = new java.util.HashMap<String,java.lang.reflect.Method>();
  private boolean _caucho_isDead;
  private boolean _caucho_isNotModified;
  private com.caucho.jsp.PageManager _jsp_pageManager;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.WebApp _jsp_application = _caucho_getApplication();
    com.caucho.jsp.PageContextImpl pageContext = _jsp_pageManager.allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true, false);

    TagState _jsp_state = new TagState();

    try {
      _jspService(request, response, pageContext, _jsp_application, session, _jsp_state);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      _jsp_state.release();
      _jsp_pageManager.freePageContext(pageContext);
    }
  }
  
  private void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response,
              com.caucho.jsp.PageContextImpl pageContext,
              javax.servlet.ServletContext application,
              javax.servlet.http.HttpSession session,
              TagState _jsp_state)
    throws Throwable
  {
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    final javax.el.ELContext _jsp_env = pageContext.getELContext();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    javax.servlet.jsp.tagext.JspTag _jsp_parent_tag = null;
    com.caucho.jsp.PageContextImpl _jsp_parentContext = pageContext;
    response.setContentType("text/html;charset=UTF-8");
    String _caucho_request_character_encoding = request.getCharacterEncoding();
    if (_caucho_request_character_encoding == null || "".equals(_caucho_request_character_encoding))
      request.setCharacterEncoding("utf-8");
    org.springframework.web.servlet.tags.form.FormTag _jsp_FormTag_0 = null;
    org.springframework.web.servlet.tags.form.HiddenInputTag _jsp_HiddenInputTag_1 = null;
    org.springframework.web.servlet.tags.form.LabelTag _jsp_LabelTag_2 = null;
    org.springframework.web.servlet.tags.form.InputTag _jsp_InputTag_3 = null;
    org.apache.shiro.web.tags.HasPermissionTag _jsp_HasPermissionTag_4 = null;
    org.springframework.web.servlet.tags.form.ButtonTag _jsp_ButtonTag_5 = null;

    out.write(_jsp_string0, 0, _jsp_string0.length);
    _caucho_expr_0.print(out, _jsp_env, false);
    out.write(_jsp_string1, 0, _jsp_string1.length);
    _jsp_FormTag_0 = _jsp_state.get_jsp_FormTag_0(pageContext, _jsp_parent_tag);
    javax.servlet.jsp.JspWriter _jsp_writer7 = out;
    try {
      int _jspEval8 = _jsp_FormTag_0.doStartTag();
      if (_jspEval8 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        out.write(_jsp_string2, 0, _jsp_string2.length);
        _jsp_HiddenInputTag_1 = _jsp_state.get_jsp_HiddenInputTag_1(pageContext, _jsp_parent_tag);
        _jsp_HiddenInputTag_1.setPath("id");
        javax.servlet.jsp.JspWriter _jsp_writer10 = out;
        try {
          int _jspEval11 = _jsp_HiddenInputTag_1.doStartTag();
        } catch (Throwable _jsp_exn_13) {
          pageContext.setWriter(_jsp_writer10);
          out = _jsp_writer10;
          _jsp_HiddenInputTag_1.doCatch(_jsp_exn_13);
        } finally {
          _jsp_HiddenInputTag_1.doFinally();
        }
        out.write(_jsp_string2, 0, _jsp_string2.length);
        _jsp_HiddenInputTag_1.setPath("available");
        javax.servlet.jsp.JspWriter _jsp_writer15 = out;
        try {
          int _jspEval16 = _jsp_HiddenInputTag_1.doStartTag();
        } catch (Throwable _jsp_exn_18) {
          pageContext.setWriter(_jsp_writer15);
          out = _jsp_writer15;
          _jsp_HiddenInputTag_1.doCatch(_jsp_exn_18);
        } finally {
          _jsp_HiddenInputTag_1.doFinally();
        }
        out.write(_jsp_string2, 0, _jsp_string2.length);
        _jsp_HiddenInputTag_1.setPath("parentId");
        javax.servlet.jsp.JspWriter _jsp_writer20 = out;
        try {
          int _jspEval21 = _jsp_HiddenInputTag_1.doStartTag();
        } catch (Throwable _jsp_exn_23) {
          pageContext.setWriter(_jsp_writer20);
          out = _jsp_writer20;
          _jsp_HiddenInputTag_1.doCatch(_jsp_exn_23);
        } finally {
          _jsp_HiddenInputTag_1.doFinally();
        }
        out.write(_jsp_string2, 0, _jsp_string2.length);
        _jsp_HiddenInputTag_1.setPath("parentIds");
        javax.servlet.jsp.JspWriter _jsp_writer25 = out;
        try {
          int _jspEval26 = _jsp_HiddenInputTag_1.doStartTag();
        } catch (Throwable _jsp_exn_28) {
          pageContext.setWriter(_jsp_writer25);
          out = _jsp_writer25;
          _jsp_HiddenInputTag_1.doCatch(_jsp_exn_28);
        } finally {
          _jsp_HiddenInputTag_1.doFinally();
        }
        out.write(_jsp_string3, 0, _jsp_string3.length);
        _jsp_LabelTag_2 = _jsp_state.get_jsp_LabelTag_2(pageContext, _jsp_parent_tag);
        javax.servlet.jsp.JspWriter _jsp_writer30 = out;
        try {
          int _jspEval31 = _jsp_LabelTag_2.doStartTag();
          if (_jspEval31 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
            out.write(_jsp_string4, 0, _jsp_string4.length);
          }
          _jsp_LabelTag_2.doEndTag();
        } catch (Throwable _jsp_exn_33) {
          pageContext.setWriter(_jsp_writer30);
          out = _jsp_writer30;
          _jsp_LabelTag_2.doCatch(_jsp_exn_33);
        } finally {
          _jsp_LabelTag_2.doFinally();
        }
        out.write(_jsp_string5, 0, _jsp_string5.length);
        _jsp_InputTag_3 = _jsp_state.get_jsp_InputTag_3(pageContext, _jsp_parent_tag);
        javax.servlet.jsp.JspWriter _jsp_writer35 = out;
        try {
          int _jspEval36 = _jsp_InputTag_3.doStartTag();
        } catch (Throwable _jsp_exn_38) {
          pageContext.setWriter(_jsp_writer35);
          out = _jsp_writer35;
          _jsp_InputTag_3.doCatch(_jsp_exn_38);
        } finally {
          _jsp_InputTag_3.doFinally();
        }
        out.write(_jsp_string6, 0, _jsp_string6.length);
        _jsp_HasPermissionTag_4 = _jsp_state.get_jsp_HasPermissionTag_4(pageContext, _jsp_parent_tag);
        _jsp_HasPermissionTag_4.setName("organization:update");
        int _jspEval41 = _jsp_HasPermissionTag_4.doStartTag();
        if (_jspEval41 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          out.write(_jsp_string5, 0, _jsp_string5.length);
          _jsp_ButtonTag_5 = _jsp_state.get_jsp_ButtonTag_5(pageContext, _jsp_parent_tag);
          _jsp_ButtonTag_5.setId("updateBtn");
          javax.servlet.jsp.JspWriter _jsp_writer43 = out;
          try {
            int _jspEval44 = _jsp_ButtonTag_5.doStartTag();
            if (_jspEval44 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
              out.write(_jsp_string7, 0, _jsp_string7.length);
            }
            _jsp_ButtonTag_5.doEndTag();
          } catch (Throwable _jsp_exn_46) {
            pageContext.setWriter(_jsp_writer43);
            out = _jsp_writer43;
            _jsp_ButtonTag_5.doCatch(_jsp_exn_46);
          } finally {
            _jsp_ButtonTag_5.doFinally();
          }
          out.write(_jsp_string2, 0, _jsp_string2.length);
        }
        out.write(_jsp_string8, 0, _jsp_string8.length);
        _jsp_HasPermissionTag_4.setName("organization:delete");
        int _jspEval50 = _jsp_HasPermissionTag_4.doStartTag();
        if (_jspEval50 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          out.write(_jsp_string5, 0, _jsp_string5.length);
          if (_caucho_expr_1.evalBoolean(_jsp_env)) {
            out.write(_jsp_string5, 0, _jsp_string5.length);
            _jsp_ButtonTag_5 = _jsp_state.get_jsp_ButtonTag_5(pageContext, _jsp_parent_tag);
            _jsp_ButtonTag_5.setId("deleteBtn");
            javax.servlet.jsp.JspWriter _jsp_writer52 = out;
            try {
              int _jspEval53 = _jsp_ButtonTag_5.doStartTag();
              if (_jspEval53 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
                out.write(_jsp_string9, 0, _jsp_string9.length);
              }
              _jsp_ButtonTag_5.doEndTag();
            } catch (Throwable _jsp_exn_55) {
              pageContext.setWriter(_jsp_writer52);
              out = _jsp_writer52;
              _jsp_ButtonTag_5.doCatch(_jsp_exn_55);
            } finally {
              _jsp_ButtonTag_5.doFinally();
            }
            out.write(_jsp_string5, 0, _jsp_string5.length);
          }
          out.write(_jsp_string2, 0, _jsp_string2.length);
        }
        out.write(_jsp_string8, 0, _jsp_string8.length);
        _jsp_HasPermissionTag_4.setName("organization:create");
        int _jspEval59 = _jsp_HasPermissionTag_4.doStartTag();
        if (_jspEval59 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          out.write(_jsp_string5, 0, _jsp_string5.length);
          _jsp_ButtonTag_5 = _jsp_state.get_jsp_ButtonTag_5(pageContext, _jsp_parent_tag);
          _jsp_ButtonTag_5.setId("appendChildBtn");
          javax.servlet.jsp.JspWriter _jsp_writer61 = out;
          try {
            int _jspEval62 = _jsp_ButtonTag_5.doStartTag();
            if (_jspEval62 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
              out.write(_jsp_string10, 0, _jsp_string10.length);
            }
            _jsp_ButtonTag_5.doEndTag();
          } catch (Throwable _jsp_exn_64) {
            pageContext.setWriter(_jsp_writer61);
            out = _jsp_writer61;
            _jsp_ButtonTag_5.doCatch(_jsp_exn_64);
          } finally {
            _jsp_ButtonTag_5.doFinally();
          }
          out.write(_jsp_string2, 0, _jsp_string2.length);
        }
        out.write(_jsp_string8, 0, _jsp_string8.length);
        _jsp_HasPermissionTag_4.setName("organization:update");
        int _jspEval68 = _jsp_HasPermissionTag_4.doStartTag();
        if (_jspEval68 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          out.write(_jsp_string5, 0, _jsp_string5.length);
          if (_caucho_expr_1.evalBoolean(_jsp_env)) {
            out.write(_jsp_string5, 0, _jsp_string5.length);
            _jsp_ButtonTag_5 = _jsp_state.get_jsp_ButtonTag_5(pageContext, _jsp_parent_tag);
            _jsp_ButtonTag_5.setId("moveBtn");
            javax.servlet.jsp.JspWriter _jsp_writer70 = out;
            try {
              int _jspEval71 = _jsp_ButtonTag_5.doStartTag();
              if (_jspEval71 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
                out.write(_jsp_string11, 0, _jsp_string11.length);
              }
              _jsp_ButtonTag_5.doEndTag();
            } catch (Throwable _jsp_exn_73) {
              pageContext.setWriter(_jsp_writer70);
              out = _jsp_writer70;
              _jsp_ButtonTag_5.doCatch(_jsp_exn_73);
            } finally {
              _jsp_ButtonTag_5.doFinally();
            }
            out.write(_jsp_string5, 0, _jsp_string5.length);
          }
          out.write(_jsp_string2, 0, _jsp_string2.length);
        }
        out.write(_jsp_string12, 0, _jsp_string12.length);
      }
      _jsp_FormTag_0.doEndTag();
    } catch (Throwable _jsp_exn_76) {
      pageContext.setWriter(_jsp_writer7);
      out = _jsp_writer7;
      _jsp_FormTag_0.doCatch(_jsp_exn_76);
    } finally {
      _jsp_FormTag_0.doFinally();
    }
    out.write(_jsp_string13, 0, _jsp_string13.length);
    _caucho_expr_0.print(out, _jsp_env, false);
    out.write(_jsp_string14, 0, _jsp_string14.length);
    _caucho_expr_0.print(out, _jsp_env, false);
    out.write(_jsp_string15, 0, _jsp_string15.length);
    _caucho_expr_2.print(out, _jsp_env, false);
    out.write(_jsp_string16, 0, _jsp_string16.length);
    _caucho_expr_0.print(out, _jsp_env, false);
    out.write(_jsp_string15, 0, _jsp_string15.length);
    _caucho_expr_2.print(out, _jsp_env, false);
    out.write(_jsp_string17, 0, _jsp_string17.length);
    _caucho_expr_0.print(out, _jsp_env, false);
    out.write(_jsp_string15, 0, _jsp_string15.length);
    _caucho_expr_2.print(out, _jsp_env, false);
    out.write(_jsp_string18, 0, _jsp_string18.length);
    _caucho_expr_0.print(out, _jsp_env, false);
    out.write(_jsp_string15, 0, _jsp_string15.length);
    _caucho_expr_2.print(out, _jsp_env, false);
    out.write(_jsp_string19, 0, _jsp_string19.length);
  }

  private com.caucho.make.DependencyContainer _caucho_depends
    = new com.caucho.make.DependencyContainer();

  public java.util.ArrayList<com.caucho.vfs.Dependency> _caucho_getDependList()
  {
    return _caucho_depends.getDependencies();
  }

  public void _caucho_addDepend(com.caucho.vfs.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    _caucho_depends.add(depend);
  }

  protected void _caucho_setNeverModified(boolean isNotModified)
  {
    _caucho_isNotModified = true;
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;

    if (_caucho_isNotModified)
      return false;

    if (com.caucho.server.util.CauchoSystem.getVersionId() != 72739197937975180L)
      return true;

    return _caucho_depends.isModified();
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
    TagState tagState;
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.server.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("WEB-INF/jsp/organization/maintain.jsp"), 6089502090566947561L, false);
    _caucho_depends.add(depend);
    depend = new com.caucho.vfs.Depend(mergePath.lookup("jar:file:/E:/Workspaces/shiro-example/shiro-example-chapter16/target/shiro-example-chapter16/WEB-INF/lib/spring-webmvc-4.0.0.RELEASE.jar!/META-INF/spring-form.tld"), 6849848904871438460L, false);
    _caucho_depends.add(depend);
    _caucho_depends.add(new com.caucho.make.ClassDependency("org.springframework.web.servlet.tags.form.HiddenInputTag", -3215122913752861492L));
    _caucho_depends.add(new com.caucho.make.ClassDependency("org.springframework.web.servlet.tags.form.LabelTag", 3828158731794487194L));
    _caucho_depends.add(new com.caucho.make.ClassDependency("org.springframework.web.servlet.tags.form.InputTag", -1062901433326805809L));
    depend = new com.caucho.vfs.Depend(mergePath.lookup("jar:file:/E:/Workspaces/shiro-example/shiro-example-chapter16/target/shiro-example-chapter16/WEB-INF/lib/shiro-web-1.2.2.jar!/META-INF/shiro.tld"), -6207406093825368018L, false);
    _caucho_depends.add(depend);
    _caucho_depends.add(new com.caucho.make.ClassDependency("org.springframework.web.servlet.tags.form.ButtonTag", 5031211284407574056L));
    _caucho_depends.add(new com.caucho.make.ClassDependency("org.apache.shiro.web.tags.HasPermissionTag", -8989021941140185354L));
    _caucho_depends.add(new com.caucho.make.ClassDependency("org.springframework.web.servlet.tags.form.FormTag", -7630901885606385127L));
  }

  static {
    try {
    } catch (Exception e) {
      e.printStackTrace();
      throw new RuntimeException(e);
    }
  }

  final static class TagState {
    private org.springframework.web.servlet.tags.form.FormTag _jsp_FormTag_0;

    final org.springframework.web.servlet.tags.form.FormTag get_jsp_FormTag_0(PageContext pageContext, javax.servlet.jsp.tagext.JspTag _jsp_parent_tag) throws Throwable
    {
      if (_jsp_FormTag_0 == null) {
        _jsp_FormTag_0 = new org.springframework.web.servlet.tags.form.FormTag();
        _jsp_FormTag_0.setPageContext(pageContext);
        if (_jsp_parent_tag instanceof javax.servlet.jsp.tagext.Tag)
          _jsp_FormTag_0.setParent((javax.servlet.jsp.tagext.Tag) _jsp_parent_tag);
        else if (_jsp_parent_tag instanceof javax.servlet.jsp.tagext.SimpleTag)
          _jsp_FormTag_0.setParent(new javax.servlet.jsp.tagext.TagAdapter((javax.servlet.jsp.tagext.SimpleTag) _jsp_parent_tag));
        else
          _jsp_FormTag_0.setParent((javax.servlet.jsp.tagext.Tag) null);
        _jsp_FormTag_0.setId("form");
        _jsp_FormTag_0.setMethod("post");
        _jsp_FormTag_0.setCommandName("organization");
      }

      return _jsp_FormTag_0;
    }
    private org.springframework.web.servlet.tags.form.HiddenInputTag _jsp_HiddenInputTag_1;

    final org.springframework.web.servlet.tags.form.HiddenInputTag get_jsp_HiddenInputTag_1(PageContext pageContext, javax.servlet.jsp.tagext.JspTag _jsp_parent_tag) throws Throwable
    {
      if (_jsp_HiddenInputTag_1 == null) {
        _jsp_HiddenInputTag_1 = new org.springframework.web.servlet.tags.form.HiddenInputTag();
        _jsp_HiddenInputTag_1.setPageContext(pageContext);
        _jsp_HiddenInputTag_1.setParent((javax.servlet.jsp.tagext.Tag) _jsp_FormTag_0);
      }

      return _jsp_HiddenInputTag_1;
    }
    private org.springframework.web.servlet.tags.form.LabelTag _jsp_LabelTag_2;

    final org.springframework.web.servlet.tags.form.LabelTag get_jsp_LabelTag_2(PageContext pageContext, javax.servlet.jsp.tagext.JspTag _jsp_parent_tag) throws Throwable
    {
      if (_jsp_LabelTag_2 == null) {
        _jsp_LabelTag_2 = new org.springframework.web.servlet.tags.form.LabelTag();
        _jsp_LabelTag_2.setPageContext(pageContext);
        _jsp_LabelTag_2.setParent((javax.servlet.jsp.tagext.Tag) _jsp_FormTag_0);
        _jsp_LabelTag_2.setPath("name");
      }

      return _jsp_LabelTag_2;
    }
    private org.springframework.web.servlet.tags.form.InputTag _jsp_InputTag_3;

    final org.springframework.web.servlet.tags.form.InputTag get_jsp_InputTag_3(PageContext pageContext, javax.servlet.jsp.tagext.JspTag _jsp_parent_tag) throws Throwable
    {
      if (_jsp_InputTag_3 == null) {
        _jsp_InputTag_3 = new org.springframework.web.servlet.tags.form.InputTag();
        _jsp_InputTag_3.setPageContext(pageContext);
        _jsp_InputTag_3.setParent((javax.servlet.jsp.tagext.Tag) _jsp_FormTag_0);
        _jsp_InputTag_3.setPath("name");
      }

      return _jsp_InputTag_3;
    }
    private org.apache.shiro.web.tags.HasPermissionTag _jsp_HasPermissionTag_4;

    final org.apache.shiro.web.tags.HasPermissionTag get_jsp_HasPermissionTag_4(PageContext pageContext, javax.servlet.jsp.tagext.JspTag _jsp_parent_tag) throws Throwable
    {
      if (_jsp_HasPermissionTag_4 == null) {
        _jsp_HasPermissionTag_4 = new org.apache.shiro.web.tags.HasPermissionTag();
        _jsp_HasPermissionTag_4.setPageContext(pageContext);
        _jsp_HasPermissionTag_4.setParent((javax.servlet.jsp.tagext.Tag) _jsp_FormTag_0);
      }

      return _jsp_HasPermissionTag_4;
    }
    private org.springframework.web.servlet.tags.form.ButtonTag _jsp_ButtonTag_5;

    final org.springframework.web.servlet.tags.form.ButtonTag get_jsp_ButtonTag_5(PageContext pageContext, javax.servlet.jsp.tagext.JspTag _jsp_parent_tag) throws Throwable
    {
      if (_jsp_ButtonTag_5 == null) {
        _jsp_ButtonTag_5 = new org.springframework.web.servlet.tags.form.ButtonTag();
        _jsp_ButtonTag_5.setPageContext(pageContext);
        _jsp_ButtonTag_5.setParent((javax.servlet.jsp.tagext.Tag) _jsp_HasPermissionTag_4);
      }

      return _jsp_ButtonTag_5;
    }

    void release()
    {
      if (_jsp_FormTag_0 != null)
        _jsp_FormTag_0.release();
      if (_jsp_HiddenInputTag_1 != null)
        _jsp_HiddenInputTag_1.release();
      if (_jsp_LabelTag_2 != null)
        _jsp_LabelTag_2.release();
      if (_jsp_InputTag_3 != null)
        _jsp_InputTag_3.release();
      if (_jsp_HasPermissionTag_4 != null)
        _jsp_HasPermissionTag_4.release();
      if (_jsp_ButtonTag_5 != null)
        _jsp_ButtonTag_5.release();
    }
  }

  public java.util.HashMap<String,java.lang.reflect.Method> _caucho_getFunctionMap()
  {
    return _jsp_functionMap;
  }

  public void caucho_init(ServletConfig config)
  {
    try {
      com.caucho.server.webapp.WebApp webApp
        = (com.caucho.server.webapp.WebApp) config.getServletContext();
      init(config);
      if (com.caucho.jsp.JspManager.getCheckInterval() >= 0)
        _caucho_depends.setCheckInterval(com.caucho.jsp.JspManager.getCheckInterval());
      _jsp_pageManager = webApp.getJspApplicationContext().getPageManager();
      com.caucho.jsp.TaglibManager manager = webApp.getJspApplicationContext().getTaglibManager();
      manager.addTaglibFunctions(_jsp_functionMap, "form", "http://www.springframework.org/tags/form");
      manager.addTaglibFunctions(_jsp_functionMap, "c", "http://java.sun.com/jsp/jstl/core");
      manager.addTaglibFunctions(_jsp_functionMap, "shiro", "http://shiro.apache.org/tags");
      com.caucho.jsp.PageContextImpl pageContext = new com.caucho.jsp.InitPageContextImpl(webApp, this);
      _caucho_expr_0 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${pageContext.request.contextPath}");
      _caucho_expr_1 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${not organization.rootNode}");
      _caucho_expr_2 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${organization.id}");
    } catch (Exception e) {
      throw com.caucho.config.ConfigException.create(e);
    }
  }
  private static com.caucho.el.Expr _caucho_expr_0;
  private static com.caucho.el.Expr _caucho_expr_1;
  private static com.caucho.el.Expr _caucho_expr_2;

  private final static char []_jsp_string2;
  private final static char []_jsp_string16;
  private final static char []_jsp_string14;
  private final static char []_jsp_string9;
  private final static char []_jsp_string1;
  private final static char []_jsp_string0;
  private final static char []_jsp_string6;
  private final static char []_jsp_string12;
  private final static char []_jsp_string5;
  private final static char []_jsp_string7;
  private final static char []_jsp_string8;
  private final static char []_jsp_string11;
  private final static char []_jsp_string17;
  private final static char []_jsp_string18;
  private final static char []_jsp_string3;
  private final static char []_jsp_string19;
  private final static char []_jsp_string15;
  private final static char []_jsp_string10;
  private final static char []_jsp_string13;
  private final static char []_jsp_string4;
  static {
    _jsp_string2 = "\n        ".toCharArray();
    _jsp_string16 = "/update\")\n                        .submit();\n                return false;\n            });\n            $(\"#deleteBtn\").click(function() {\n                if(confirm(\"\u786e\u8ba4\u5220\u9664\u5417\uff1f\")) {\n                    $(\"#form\")\n                            .attr(\"action\", \"".toCharArray();
    _jsp_string14 = "/static/js/jquery-1.11.0.min.js\"></script>\n    <script>\n        $(function() {\n            $(\"#updateBtn\").click(function() {\n                $(\"#form\")\n                        .attr(\"action\", \"".toCharArray();
    _jsp_string9 = "\u5220\u9664".toCharArray();
    _jsp_string1 = "/static/css/css.css\">\n</head>\n<body>\n\n    ".toCharArray();
    _jsp_string0 = "\n\n\n\n\n<html>\n<head>\n    <title></title>\n    <link rel=\"stylesheet\" href=\"".toCharArray();
    _jsp_string6 = "\n        </div>\n        ".toCharArray();
    _jsp_string12 = "\n    ".toCharArray();
    _jsp_string5 = "\n            ".toCharArray();
    _jsp_string7 = "\u4fee\u6539".toCharArray();
    _jsp_string8 = "\n\n        ".toCharArray();
    _jsp_string11 = "\u79fb\u52a8\u8282\u70b9".toCharArray();
    _jsp_string17 = "/delete\")\n                            .submit();\n                }\n                return false;\n            });\n            $(\"#appendChildBtn\").click(function() {\n                location.href=\"".toCharArray();
    _jsp_string18 = "/appendChild\";\n                return false;\n            });\n            $(\"#moveBtn\").click(function() {\n                location.href=\"".toCharArray();
    _jsp_string3 = "\n\n        <div class=\"form-group\">\n            ".toCharArray();
    _jsp_string19 = "/move\";\n                return false;\n            });\n        });\n    </script>\n</body>\n</html>".toCharArray();
    _jsp_string15 = "/organization/".toCharArray();
    _jsp_string10 = "\u6dfb\u52a0\u5b50\u8282\u70b9".toCharArray();
    _jsp_string13 = "\n\n    <script src=\"".toCharArray();
    _jsp_string4 = "\u540d\u79f0\uff1a".toCharArray();
  }
}
