/*
 * JSP generated by Resin Professional 4.0.13 (built Tue, 09 Nov 2010 03:50:16 PST)
 */

package _jsp;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;

public class _index__jsp extends com.caucho.jsp.JavaPage
{
  private static final java.util.HashMap<String,java.lang.reflect.Method> _jsp_functionMap = new java.util.HashMap<String,java.lang.reflect.Method>();
  private boolean _caucho_isDead;
  private boolean _caucho_isNotModified;
  private com.caucho.jsp.PageManager _jsp_pageManager;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.WebApp _jsp_application = _caucho_getApplication();
    com.caucho.jsp.PageContextImpl pageContext = _jsp_pageManager.allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true, false);

    TagState _jsp_state = new TagState();

    try {
      _jspService(request, response, pageContext, _jsp_application, session, _jsp_state);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      _jsp_state.release();
      _jsp_pageManager.freePageContext(pageContext);
    }
  }
  
  private void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response,
              com.caucho.jsp.PageContextImpl pageContext,
              javax.servlet.ServletContext application,
              javax.servlet.http.HttpSession session,
              TagState _jsp_state)
    throws Throwable
  {
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    final javax.el.ELContext _jsp_env = pageContext.getELContext();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    javax.servlet.jsp.tagext.JspTag _jsp_parent_tag = null;
    com.caucho.jsp.PageContextImpl _jsp_parentContext = pageContext;
    response.setContentType("text/html;charset=UTF-8");
    String _caucho_request_character_encoding = request.getCharacterEncoding();
    if (_caucho_request_character_encoding == null || "".equals(_caucho_request_character_encoding))
      request.setCharacterEncoding("utf-8");
    org.apache.shiro.web.tags.GuestTag _jsp_GuestTag_3 = null;
    org.apache.shiro.web.tags.UserTag _jsp_UserTag_4 = null;
    org.apache.shiro.web.tags.PrincipalTag _jsp_PrincipalTag_5 = null;
    org.apache.shiro.web.tags.AuthenticatedTag _jsp_AuthenticatedTag_6 = null;
    org.apache.shiro.web.tags.PrincipalTag _jsp_PrincipalTag_7 = null;
    org.apache.shiro.web.tags.NotAuthenticatedTag _jsp_NotAuthenticatedTag_8 = null;
    org.apache.shiro.web.tags.HasRoleTag _jsp_HasRoleTag_9 = null;
    org.apache.shiro.web.tags.PrincipalTag _jsp_PrincipalTag_10 = null;
    org.apache.shiro.web.tags.HasAnyRolesTag _jsp_HasAnyRolesTag_11 = null;
    org.apache.shiro.web.tags.PrincipalTag _jsp_PrincipalTag_12 = null;
    org.apache.shiro.web.tags.LacksRoleTag _jsp_LacksRoleTag_13 = null;
    org.apache.shiro.web.tags.PrincipalTag _jsp_PrincipalTag_14 = null;
    org.apache.shiro.web.tags.HasPermissionTag _jsp_HasPermissionTag_15 = null;
    org.apache.shiro.web.tags.PrincipalTag _jsp_PrincipalTag_16 = null;
    org.apache.shiro.web.tags.LacksPermissionTag _jsp_LacksPermissionTag_17 = null;
    org.apache.shiro.web.tags.PrincipalTag _jsp_PrincipalTag_18 = null;
    _jsp._web_22dinf._tags._hasallroles__tag _jsp__hasallroles__tag_19 = null;
    _CauchoFragment_0 _jsp_fragment_0 = null;
    javax.servlet.jsp.tagext.Tag _jsp__hasallroles__tag_19_adapter = null;
    _jsp._web_22dinf._tags._hasallpermissions__tag _jsp__hasallpermissions__tag_20 = null;
    _CauchoFragment_1 _jsp_fragment_1 = null;
    javax.servlet.jsp.tagext.Tag _jsp__hasallpermissions__tag_20_adapter = null;
    _jsp._web_22dinf._tags._hasanypermissions__tag _jsp__hasanypermissions__tag_21 = null;
    _CauchoFragment_2 _jsp_fragment_2 = null;
    javax.servlet.jsp.tagext.Tag _jsp__hasanypermissions__tag_21_adapter = null;

    out.write(_jsp_string0, 0, _jsp_string0.length);
    _jsp_GuestTag_3 = _jsp_state.get_jsp_GuestTag_3(pageContext, _jsp_parent_tag);
    int _jspEval24 = _jsp_GuestTag_3.doStartTag();
    if (_jspEval24 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      out.write(_jsp_string1, 0, _jsp_string1.length);
      _caucho_expr_0.print(out, _jsp_env, false);
      out.write(_jsp_string2, 0, _jsp_string2.length);
    }
    out.write(_jsp_string3, 0, _jsp_string3.length);
    _jsp_UserTag_4 = _jsp_state.get_jsp_UserTag_4(pageContext, _jsp_parent_tag);
    int _jspEval28 = _jsp_UserTag_4.doStartTag();
    if (_jspEval28 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      out.write(_jsp_string4, 0, _jsp_string4.length);
      _jsp_PrincipalTag_5 = _jsp_state.get_jsp_PrincipalTag_5(pageContext, _jsp_parent_tag);
      _jsp_PrincipalTag_5.doStartTag();
      out.write(_jsp_string5, 0, _jsp_string5.length);
      _caucho_expr_0.print(out, _jsp_env, false);
      out.write(_jsp_string6, 0, _jsp_string6.length);
    }
    out.write(_jsp_string7, 0, _jsp_string7.length);
    _jsp_AuthenticatedTag_6 = _jsp_state.get_jsp_AuthenticatedTag_6(pageContext, _jsp_parent_tag);
    int _jspEval36 = _jsp_AuthenticatedTag_6.doStartTag();
    if (_jspEval36 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      out.write(_jsp_string8, 0, _jsp_string8.length);
      _jsp_PrincipalTag_7 = _jsp_state.get_jsp_PrincipalTag_7(pageContext, _jsp_parent_tag);
      _jsp_PrincipalTag_7.doStartTag();
      out.write(_jsp_string9, 0, _jsp_string9.length);
    }
    out.write(_jsp_string10, 0, _jsp_string10.length);
    _jsp_NotAuthenticatedTag_8 = _jsp_state.get_jsp_NotAuthenticatedTag_8(pageContext, _jsp_parent_tag);
    int _jspEval44 = _jsp_NotAuthenticatedTag_8.doStartTag();
    if (_jspEval44 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      out.write(_jsp_string11, 0, _jsp_string11.length);
    }
    out.write(_jsp_string12, 0, _jsp_string12.length);
    _jsp_HasRoleTag_9 = _jsp_state.get_jsp_HasRoleTag_9(pageContext, _jsp_parent_tag);
    int _jspEval48 = _jsp_HasRoleTag_9.doStartTag();
    if (_jspEval48 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      out.write(_jsp_string8, 0, _jsp_string8.length);
      _jsp_PrincipalTag_10 = _jsp_state.get_jsp_PrincipalTag_10(pageContext, _jsp_parent_tag);
      _jsp_PrincipalTag_10.doStartTag();
      out.write(_jsp_string13, 0, _jsp_string13.length);
    }
    out.write(_jsp_string14, 0, _jsp_string14.length);
    _jsp_HasAnyRolesTag_11 = _jsp_state.get_jsp_HasAnyRolesTag_11(pageContext, _jsp_parent_tag);
    int _jspEval56 = _jsp_HasAnyRolesTag_11.doStartTag();
    if (_jspEval56 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      out.write(_jsp_string8, 0, _jsp_string8.length);
      _jsp_PrincipalTag_12 = _jsp_state.get_jsp_PrincipalTag_12(pageContext, _jsp_parent_tag);
      _jsp_PrincipalTag_12.doStartTag();
      out.write(_jsp_string15, 0, _jsp_string15.length);
    }
    out.write(_jsp_string16, 0, _jsp_string16.length);
    _jsp_LacksRoleTag_13 = _jsp_state.get_jsp_LacksRoleTag_13(pageContext, _jsp_parent_tag);
    int _jspEval64 = _jsp_LacksRoleTag_13.doStartTag();
    if (_jspEval64 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      out.write(_jsp_string8, 0, _jsp_string8.length);
      _jsp_PrincipalTag_14 = _jsp_state.get_jsp_PrincipalTag_14(pageContext, _jsp_parent_tag);
      _jsp_PrincipalTag_14.doStartTag();
      out.write(_jsp_string17, 0, _jsp_string17.length);
    }
    out.write(_jsp_string18, 0, _jsp_string18.length);
    _jsp_HasPermissionTag_15 = _jsp_state.get_jsp_HasPermissionTag_15(pageContext, _jsp_parent_tag);
    int _jspEval72 = _jsp_HasPermissionTag_15.doStartTag();
    if (_jspEval72 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      out.write(_jsp_string8, 0, _jsp_string8.length);
      _jsp_PrincipalTag_16 = _jsp_state.get_jsp_PrincipalTag_16(pageContext, _jsp_parent_tag);
      _jsp_PrincipalTag_16.doStartTag();
      out.write(_jsp_string19, 0, _jsp_string19.length);
    }
    out.write(_jsp_string20, 0, _jsp_string20.length);
    _jsp_LacksPermissionTag_17 = _jsp_state.get_jsp_LacksPermissionTag_17(pageContext, _jsp_parent_tag);
    int _jspEval80 = _jsp_LacksPermissionTag_17.doStartTag();
    if (_jspEval80 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      out.write(_jsp_string8, 0, _jsp_string8.length);
      _jsp_PrincipalTag_18 = _jsp_state.get_jsp_PrincipalTag_18(pageContext, _jsp_parent_tag);
      _jsp_PrincipalTag_18.doStartTag();
      out.write(_jsp_string21, 0, _jsp_string21.length);
    }
    out.write(_jsp_string20, 0, _jsp_string20.length);
    _jsp__hasallroles__tag_19 = new _jsp._web_22dinf._tags._hasallroles__tag();
    _jsp__hasallroles__tag_19.setJspContext(pageContext);
    _jsp__hasallroles__tag_19_adapter = new javax.servlet.jsp.tagext.TagAdapter(_jsp__hasallroles__tag_19);
    _jsp__hasallroles__tag_19.setName("admin,user");
    _jsp__hasallroles__tag_19.setJspBody(_jsp_fragment_0 = createFragment_0(null, _jsp_parentContext, pageContext, _jsp__hasallroles__tag_19_adapter, null, _jsp_state, _jsp_pageManager));
    _jsp__hasallroles__tag_19.doTag();
    out.write(_jsp_string20, 0, _jsp_string20.length);
    _jsp__hasallpermissions__tag_20 = new _jsp._web_22dinf._tags._hasallpermissions__tag();
    _jsp__hasallpermissions__tag_20.setJspContext(pageContext);
    _jsp__hasallpermissions__tag_20_adapter = new javax.servlet.jsp.tagext.TagAdapter(_jsp__hasallpermissions__tag_20);
    _jsp__hasallpermissions__tag_20.setName("user:create,user:update");
    _jsp__hasallpermissions__tag_20.setJspBody(_jsp_fragment_1 = createFragment_1(null, _jsp_parentContext, pageContext, _jsp__hasallpermissions__tag_20_adapter, null, _jsp_state, _jsp_pageManager));
    _jsp__hasallpermissions__tag_20.doTag();
    out.write(_jsp_string20, 0, _jsp_string20.length);
    _jsp__hasanypermissions__tag_21 = new _jsp._web_22dinf._tags._hasanypermissions__tag();
    _jsp__hasanypermissions__tag_21.setJspContext(pageContext);
    _jsp__hasanypermissions__tag_21_adapter = new javax.servlet.jsp.tagext.TagAdapter(_jsp__hasanypermissions__tag_21);
    _jsp__hasanypermissions__tag_21.setName("user:create,abc:update");
    _jsp__hasanypermissions__tag_21.setJspBody(_jsp_fragment_2 = createFragment_2(null, _jsp_parentContext, pageContext, _jsp__hasanypermissions__tag_21_adapter, null, _jsp_state, _jsp_pageManager));
    _jsp__hasanypermissions__tag_21.doTag();
    out.write(_jsp_string22, 0, _jsp_string22.length);
  }

  _CauchoFragment_0 createFragment_0(_CauchoFragment_0 frag,
                                 javax.servlet.jsp.JspContext _jsp_parentContext,
                                 com.caucho.jsp.PageContextImpl pageContext,
                                 javax.servlet.jsp.tagext.JspTag parent,
                                 javax.servlet.jsp.tagext.JspFragment jspBody,
                                 TagState _jsp_state,
                                 com.caucho.jsp.PageManager _jsp_pageManager)
  {
    if (frag == null) {
      frag = new _CauchoFragment_0(_jsp_parentContext,
                   pageContext, parent, jspBody, _jsp_state,
                   _jsp_pageManager);
    }


    return frag;
  }
  public class _CauchoFragment_0 extends com.caucho.jsp.JspFragmentSupport {
    private TagState _jsp_state;
    _CauchoFragment_0(
                    javax.servlet.jsp.JspContext _jsp_parentContext,
                    com.caucho.jsp.PageContextImpl pageContext,
                    javax.servlet.jsp.tagext.JspTag parent,
                    javax.servlet.jsp.tagext.JspFragment jspBody,
                    TagState _jsp_state,
                    com.caucho.jsp.PageManager _jsp_pageManager)
    {
      this._jsp_parentContext = _jsp_parentContext;
      this.pageContext = pageContext;
      this._jsp_env = pageContext.getELContext();
      this._jsp_parent_tag = parent;
      this._jspBody = jspBody;
      this._jsp_state = _jsp_state;
      this._jsp_pageManager = _jsp_pageManager;
    }

    protected void _jsp_invoke(JspWriter out)
      throws Throwable
    {
      org.apache.shiro.web.tags.PrincipalTag _jsp_PrincipalTag_86 = null;
      out.write(_jsp_string8, 0, _jsp_string8.length);
      _jsp_PrincipalTag_86 = _jsp_state.get_jsp_PrincipalTag_86(pageContext, _jsp_parent_tag);
      _jsp_PrincipalTag_86.doStartTag();
      out.write(_jsp_string23, 0, _jsp_string23.length);
    }
  }

  _CauchoFragment_1 createFragment_1(_CauchoFragment_1 frag,
                                 javax.servlet.jsp.JspContext _jsp_parentContext,
                                 com.caucho.jsp.PageContextImpl pageContext,
                                 javax.servlet.jsp.tagext.JspTag parent,
                                 javax.servlet.jsp.tagext.JspFragment jspBody,
                                 TagState _jsp_state,
                                 com.caucho.jsp.PageManager _jsp_pageManager)
  {
    if (frag == null) {
      frag = new _CauchoFragment_1(_jsp_parentContext,
                   pageContext, parent, jspBody, _jsp_state,
                   _jsp_pageManager);
    }


    return frag;
  }
  public class _CauchoFragment_1 extends com.caucho.jsp.JspFragmentSupport {
    private TagState _jsp_state;
    _CauchoFragment_1(
                    javax.servlet.jsp.JspContext _jsp_parentContext,
                    com.caucho.jsp.PageContextImpl pageContext,
                    javax.servlet.jsp.tagext.JspTag parent,
                    javax.servlet.jsp.tagext.JspFragment jspBody,
                    TagState _jsp_state,
                    com.caucho.jsp.PageManager _jsp_pageManager)
    {
      this._jsp_parentContext = _jsp_parentContext;
      this.pageContext = pageContext;
      this._jsp_env = pageContext.getELContext();
      this._jsp_parent_tag = parent;
      this._jspBody = jspBody;
      this._jsp_state = _jsp_state;
      this._jsp_pageManager = _jsp_pageManager;
    }

    protected void _jsp_invoke(JspWriter out)
      throws Throwable
    {
      org.apache.shiro.web.tags.PrincipalTag _jsp_PrincipalTag_91 = null;
      out.write(_jsp_string8, 0, _jsp_string8.length);
      _jsp_PrincipalTag_91 = _jsp_state.get_jsp_PrincipalTag_91(pageContext, _jsp_parent_tag);
      _jsp_PrincipalTag_91.doStartTag();
      out.write(_jsp_string24, 0, _jsp_string24.length);
    }
  }

  _CauchoFragment_2 createFragment_2(_CauchoFragment_2 frag,
                                 javax.servlet.jsp.JspContext _jsp_parentContext,
                                 com.caucho.jsp.PageContextImpl pageContext,
                                 javax.servlet.jsp.tagext.JspTag parent,
                                 javax.servlet.jsp.tagext.JspFragment jspBody,
                                 TagState _jsp_state,
                                 com.caucho.jsp.PageManager _jsp_pageManager)
  {
    if (frag == null) {
      frag = new _CauchoFragment_2(_jsp_parentContext,
                   pageContext, parent, jspBody, _jsp_state,
                   _jsp_pageManager);
    }


    return frag;
  }
  public class _CauchoFragment_2 extends com.caucho.jsp.JspFragmentSupport {
    private TagState _jsp_state;
    _CauchoFragment_2(
                    javax.servlet.jsp.JspContext _jsp_parentContext,
                    com.caucho.jsp.PageContextImpl pageContext,
                    javax.servlet.jsp.tagext.JspTag parent,
                    javax.servlet.jsp.tagext.JspFragment jspBody,
                    TagState _jsp_state,
                    com.caucho.jsp.PageManager _jsp_pageManager)
    {
      this._jsp_parentContext = _jsp_parentContext;
      this.pageContext = pageContext;
      this._jsp_env = pageContext.getELContext();
      this._jsp_parent_tag = parent;
      this._jspBody = jspBody;
      this._jsp_state = _jsp_state;
      this._jsp_pageManager = _jsp_pageManager;
    }

    protected void _jsp_invoke(JspWriter out)
      throws Throwable
    {
      org.apache.shiro.web.tags.PrincipalTag _jsp_PrincipalTag_96 = null;
      out.write(_jsp_string8, 0, _jsp_string8.length);
      _jsp_PrincipalTag_96 = _jsp_state.get_jsp_PrincipalTag_96(pageContext, _jsp_parent_tag);
      _jsp_PrincipalTag_96.doStartTag();
      out.write(_jsp_string25, 0, _jsp_string25.length);
    }
  }

  private com.caucho.make.DependencyContainer _caucho_depends
    = new com.caucho.make.DependencyContainer();

  public java.util.ArrayList<com.caucho.vfs.Dependency> _caucho_getDependList()
  {
    return _caucho_depends.getDependencies();
  }

  public void _caucho_addDepend(com.caucho.vfs.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    _caucho_depends.add(depend);
  }

  protected void _caucho_setNeverModified(boolean isNotModified)
  {
    _caucho_isNotModified = true;
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;

    if (_caucho_isNotModified)
      return false;

    if (com.caucho.server.util.CauchoSystem.getVersionId() != 72739197937975180L)
      return true;

    return _caucho_depends.isModified();
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
    TagState tagState;
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.server.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("index.jsp"), -8610790809904624203L, false);
    _caucho_depends.add(depend);
    depend = new com.caucho.vfs.Depend(mergePath.lookup("jar:file:/E:/Workspaces/shiro-example/shiro-example-chapter9/target/shiro-example-chapter9/WEB-INF/lib/shiro-web-1.2.2.jar!/META-INF/shiro.tld"), -6207406093825368018L, false);
    _caucho_depends.add(depend);
    _caucho_depends.add(new com.caucho.make.ClassDependency("org.apache.shiro.web.tags.GuestTag", 5701916638987586964L));
    _caucho_depends.add(new com.caucho.make.ClassDependency("org.apache.shiro.web.tags.PrincipalTag", -4653556525534072090L));
    _caucho_depends.add(new com.caucho.make.ClassDependency("org.apache.shiro.web.tags.UserTag", 6694308417190239424L));
    _caucho_depends.add(new com.caucho.make.ClassDependency("org.apache.shiro.web.tags.AuthenticatedTag", -6708547476368241071L));
    _caucho_depends.add(new com.caucho.make.ClassDependency("org.apache.shiro.web.tags.NotAuthenticatedTag", -5847934255102968464L));
    _caucho_depends.add(new com.caucho.make.ClassDependency("org.apache.shiro.web.tags.HasRoleTag", -5114212295884409060L));
    _caucho_depends.add(new com.caucho.make.ClassDependency("org.apache.shiro.web.tags.HasAnyRolesTag", -2674478841075511402L));
    _caucho_depends.add(new com.caucho.make.ClassDependency("org.apache.shiro.web.tags.LacksRoleTag", 914406398175522436L));
    _caucho_depends.add(new com.caucho.make.ClassDependency("org.apache.shiro.web.tags.HasPermissionTag", -8989021941140185354L));
    _caucho_depends.add(new com.caucho.make.ClassDependency("org.apache.shiro.web.tags.LacksPermissionTag", -6326505090083738816L));
    depend = new com.caucho.vfs.Depend(appDir.lookup("WEB-INF/tags/hasAllRoles.tag"), -6841156820573012322L, false);
    _caucho_depends.add(depend);
    depend = new com.caucho.vfs.Depend(appDir.lookup("WEB-INF/tags/hasAllPermissions.tag"), -3261538421091502042L, false);
    _caucho_depends.add(depend);
    depend = new com.caucho.vfs.Depend(appDir.lookup("WEB-INF/tags/hasAnyPermissions.tag"), 2542878755723048592L, false);
    _caucho_depends.add(depend);
  }

  static {
    try {
    } catch (Exception e) {
      e.printStackTrace();
      throw new RuntimeException(e);
    }
  }

  final static class TagState {
    private org.apache.shiro.web.tags.GuestTag _jsp_GuestTag_3;

    final org.apache.shiro.web.tags.GuestTag get_jsp_GuestTag_3(PageContext pageContext, javax.servlet.jsp.tagext.JspTag _jsp_parent_tag) throws Throwable
    {
      if (_jsp_GuestTag_3 == null) {
        _jsp_GuestTag_3 = new org.apache.shiro.web.tags.GuestTag();
        _jsp_GuestTag_3.setPageContext(pageContext);
        if (_jsp_parent_tag instanceof javax.servlet.jsp.tagext.Tag)
          _jsp_GuestTag_3.setParent((javax.servlet.jsp.tagext.Tag) _jsp_parent_tag);
        else if (_jsp_parent_tag instanceof javax.servlet.jsp.tagext.SimpleTag)
          _jsp_GuestTag_3.setParent(new javax.servlet.jsp.tagext.TagAdapter((javax.servlet.jsp.tagext.SimpleTag) _jsp_parent_tag));
        else
          _jsp_GuestTag_3.setParent((javax.servlet.jsp.tagext.Tag) null);
      }

      return _jsp_GuestTag_3;
    }
    private org.apache.shiro.web.tags.UserTag _jsp_UserTag_4;

    final org.apache.shiro.web.tags.UserTag get_jsp_UserTag_4(PageContext pageContext, javax.servlet.jsp.tagext.JspTag _jsp_parent_tag) throws Throwable
    {
      if (_jsp_UserTag_4 == null) {
        _jsp_UserTag_4 = new org.apache.shiro.web.tags.UserTag();
        _jsp_UserTag_4.setPageContext(pageContext);
        if (_jsp_parent_tag instanceof javax.servlet.jsp.tagext.Tag)
          _jsp_UserTag_4.setParent((javax.servlet.jsp.tagext.Tag) _jsp_parent_tag);
        else if (_jsp_parent_tag instanceof javax.servlet.jsp.tagext.SimpleTag)
          _jsp_UserTag_4.setParent(new javax.servlet.jsp.tagext.TagAdapter((javax.servlet.jsp.tagext.SimpleTag) _jsp_parent_tag));
        else
          _jsp_UserTag_4.setParent((javax.servlet.jsp.tagext.Tag) null);
      }

      return _jsp_UserTag_4;
    }
    private org.apache.shiro.web.tags.PrincipalTag _jsp_PrincipalTag_5;

    final org.apache.shiro.web.tags.PrincipalTag get_jsp_PrincipalTag_5(PageContext pageContext, javax.servlet.jsp.tagext.JspTag _jsp_parent_tag) throws Throwable
    {
      if (_jsp_PrincipalTag_5 == null) {
        _jsp_PrincipalTag_5 = new org.apache.shiro.web.tags.PrincipalTag();
        _jsp_PrincipalTag_5.setPageContext(pageContext);
        _jsp_PrincipalTag_5.setParent((javax.servlet.jsp.tagext.Tag) _jsp_UserTag_4);
      }

      return _jsp_PrincipalTag_5;
    }
    private org.apache.shiro.web.tags.AuthenticatedTag _jsp_AuthenticatedTag_6;

    final org.apache.shiro.web.tags.AuthenticatedTag get_jsp_AuthenticatedTag_6(PageContext pageContext, javax.servlet.jsp.tagext.JspTag _jsp_parent_tag) throws Throwable
    {
      if (_jsp_AuthenticatedTag_6 == null) {
        _jsp_AuthenticatedTag_6 = new org.apache.shiro.web.tags.AuthenticatedTag();
        _jsp_AuthenticatedTag_6.setPageContext(pageContext);
        if (_jsp_parent_tag instanceof javax.servlet.jsp.tagext.Tag)
          _jsp_AuthenticatedTag_6.setParent((javax.servlet.jsp.tagext.Tag) _jsp_parent_tag);
        else if (_jsp_parent_tag instanceof javax.servlet.jsp.tagext.SimpleTag)
          _jsp_AuthenticatedTag_6.setParent(new javax.servlet.jsp.tagext.TagAdapter((javax.servlet.jsp.tagext.SimpleTag) _jsp_parent_tag));
        else
          _jsp_AuthenticatedTag_6.setParent((javax.servlet.jsp.tagext.Tag) null);
      }

      return _jsp_AuthenticatedTag_6;
    }
    private org.apache.shiro.web.tags.PrincipalTag _jsp_PrincipalTag_7;

    final org.apache.shiro.web.tags.PrincipalTag get_jsp_PrincipalTag_7(PageContext pageContext, javax.servlet.jsp.tagext.JspTag _jsp_parent_tag) throws Throwable
    {
      if (_jsp_PrincipalTag_7 == null) {
        _jsp_PrincipalTag_7 = new org.apache.shiro.web.tags.PrincipalTag();
        _jsp_PrincipalTag_7.setPageContext(pageContext);
        _jsp_PrincipalTag_7.setParent((javax.servlet.jsp.tagext.Tag) _jsp_AuthenticatedTag_6);
      }

      return _jsp_PrincipalTag_7;
    }
    private org.apache.shiro.web.tags.NotAuthenticatedTag _jsp_NotAuthenticatedTag_8;

    final org.apache.shiro.web.tags.NotAuthenticatedTag get_jsp_NotAuthenticatedTag_8(PageContext pageContext, javax.servlet.jsp.tagext.JspTag _jsp_parent_tag) throws Throwable
    {
      if (_jsp_NotAuthenticatedTag_8 == null) {
        _jsp_NotAuthenticatedTag_8 = new org.apache.shiro.web.tags.NotAuthenticatedTag();
        _jsp_NotAuthenticatedTag_8.setPageContext(pageContext);
        if (_jsp_parent_tag instanceof javax.servlet.jsp.tagext.Tag)
          _jsp_NotAuthenticatedTag_8.setParent((javax.servlet.jsp.tagext.Tag) _jsp_parent_tag);
        else if (_jsp_parent_tag instanceof javax.servlet.jsp.tagext.SimpleTag)
          _jsp_NotAuthenticatedTag_8.setParent(new javax.servlet.jsp.tagext.TagAdapter((javax.servlet.jsp.tagext.SimpleTag) _jsp_parent_tag));
        else
          _jsp_NotAuthenticatedTag_8.setParent((javax.servlet.jsp.tagext.Tag) null);
      }

      return _jsp_NotAuthenticatedTag_8;
    }
    private org.apache.shiro.web.tags.HasRoleTag _jsp_HasRoleTag_9;

    final org.apache.shiro.web.tags.HasRoleTag get_jsp_HasRoleTag_9(PageContext pageContext, javax.servlet.jsp.tagext.JspTag _jsp_parent_tag) throws Throwable
    {
      if (_jsp_HasRoleTag_9 == null) {
        _jsp_HasRoleTag_9 = new org.apache.shiro.web.tags.HasRoleTag();
        _jsp_HasRoleTag_9.setPageContext(pageContext);
        if (_jsp_parent_tag instanceof javax.servlet.jsp.tagext.Tag)
          _jsp_HasRoleTag_9.setParent((javax.servlet.jsp.tagext.Tag) _jsp_parent_tag);
        else if (_jsp_parent_tag instanceof javax.servlet.jsp.tagext.SimpleTag)
          _jsp_HasRoleTag_9.setParent(new javax.servlet.jsp.tagext.TagAdapter((javax.servlet.jsp.tagext.SimpleTag) _jsp_parent_tag));
        else
          _jsp_HasRoleTag_9.setParent((javax.servlet.jsp.tagext.Tag) null);
        _jsp_HasRoleTag_9.setName("admin");
      }

      return _jsp_HasRoleTag_9;
    }
    private org.apache.shiro.web.tags.PrincipalTag _jsp_PrincipalTag_10;

    final org.apache.shiro.web.tags.PrincipalTag get_jsp_PrincipalTag_10(PageContext pageContext, javax.servlet.jsp.tagext.JspTag _jsp_parent_tag) throws Throwable
    {
      if (_jsp_PrincipalTag_10 == null) {
        _jsp_PrincipalTag_10 = new org.apache.shiro.web.tags.PrincipalTag();
        _jsp_PrincipalTag_10.setPageContext(pageContext);
        _jsp_PrincipalTag_10.setParent((javax.servlet.jsp.tagext.Tag) _jsp_HasRoleTag_9);
      }

      return _jsp_PrincipalTag_10;
    }
    private org.apache.shiro.web.tags.HasAnyRolesTag _jsp_HasAnyRolesTag_11;

    final org.apache.shiro.web.tags.HasAnyRolesTag get_jsp_HasAnyRolesTag_11(PageContext pageContext, javax.servlet.jsp.tagext.JspTag _jsp_parent_tag) throws Throwable
    {
      if (_jsp_HasAnyRolesTag_11 == null) {
        _jsp_HasAnyRolesTag_11 = new org.apache.shiro.web.tags.HasAnyRolesTag();
        _jsp_HasAnyRolesTag_11.setPageContext(pageContext);
        if (_jsp_parent_tag instanceof javax.servlet.jsp.tagext.Tag)
          _jsp_HasAnyRolesTag_11.setParent((javax.servlet.jsp.tagext.Tag) _jsp_parent_tag);
        else if (_jsp_parent_tag instanceof javax.servlet.jsp.tagext.SimpleTag)
          _jsp_HasAnyRolesTag_11.setParent(new javax.servlet.jsp.tagext.TagAdapter((javax.servlet.jsp.tagext.SimpleTag) _jsp_parent_tag));
        else
          _jsp_HasAnyRolesTag_11.setParent((javax.servlet.jsp.tagext.Tag) null);
        _jsp_HasAnyRolesTag_11.setName("admin,user");
      }

      return _jsp_HasAnyRolesTag_11;
    }
    private org.apache.shiro.web.tags.PrincipalTag _jsp_PrincipalTag_12;

    final org.apache.shiro.web.tags.PrincipalTag get_jsp_PrincipalTag_12(PageContext pageContext, javax.servlet.jsp.tagext.JspTag _jsp_parent_tag) throws Throwable
    {
      if (_jsp_PrincipalTag_12 == null) {
        _jsp_PrincipalTag_12 = new org.apache.shiro.web.tags.PrincipalTag();
        _jsp_PrincipalTag_12.setPageContext(pageContext);
        _jsp_PrincipalTag_12.setParent((javax.servlet.jsp.tagext.Tag) _jsp_HasAnyRolesTag_11);
      }

      return _jsp_PrincipalTag_12;
    }
    private org.apache.shiro.web.tags.LacksRoleTag _jsp_LacksRoleTag_13;

    final org.apache.shiro.web.tags.LacksRoleTag get_jsp_LacksRoleTag_13(PageContext pageContext, javax.servlet.jsp.tagext.JspTag _jsp_parent_tag) throws Throwable
    {
      if (_jsp_LacksRoleTag_13 == null) {
        _jsp_LacksRoleTag_13 = new org.apache.shiro.web.tags.LacksRoleTag();
        _jsp_LacksRoleTag_13.setPageContext(pageContext);
        if (_jsp_parent_tag instanceof javax.servlet.jsp.tagext.Tag)
          _jsp_LacksRoleTag_13.setParent((javax.servlet.jsp.tagext.Tag) _jsp_parent_tag);
        else if (_jsp_parent_tag instanceof javax.servlet.jsp.tagext.SimpleTag)
          _jsp_LacksRoleTag_13.setParent(new javax.servlet.jsp.tagext.TagAdapter((javax.servlet.jsp.tagext.SimpleTag) _jsp_parent_tag));
        else
          _jsp_LacksRoleTag_13.setParent((javax.servlet.jsp.tagext.Tag) null);
        _jsp_LacksRoleTag_13.setName("abc");
      }

      return _jsp_LacksRoleTag_13;
    }
    private org.apache.shiro.web.tags.PrincipalTag _jsp_PrincipalTag_14;

    final org.apache.shiro.web.tags.PrincipalTag get_jsp_PrincipalTag_14(PageContext pageContext, javax.servlet.jsp.tagext.JspTag _jsp_parent_tag) throws Throwable
    {
      if (_jsp_PrincipalTag_14 == null) {
        _jsp_PrincipalTag_14 = new org.apache.shiro.web.tags.PrincipalTag();
        _jsp_PrincipalTag_14.setPageContext(pageContext);
        _jsp_PrincipalTag_14.setParent((javax.servlet.jsp.tagext.Tag) _jsp_LacksRoleTag_13);
      }

      return _jsp_PrincipalTag_14;
    }
    private org.apache.shiro.web.tags.HasPermissionTag _jsp_HasPermissionTag_15;

    final org.apache.shiro.web.tags.HasPermissionTag get_jsp_HasPermissionTag_15(PageContext pageContext, javax.servlet.jsp.tagext.JspTag _jsp_parent_tag) throws Throwable
    {
      if (_jsp_HasPermissionTag_15 == null) {
        _jsp_HasPermissionTag_15 = new org.apache.shiro.web.tags.HasPermissionTag();
        _jsp_HasPermissionTag_15.setPageContext(pageContext);
        if (_jsp_parent_tag instanceof javax.servlet.jsp.tagext.Tag)
          _jsp_HasPermissionTag_15.setParent((javax.servlet.jsp.tagext.Tag) _jsp_parent_tag);
        else if (_jsp_parent_tag instanceof javax.servlet.jsp.tagext.SimpleTag)
          _jsp_HasPermissionTag_15.setParent(new javax.servlet.jsp.tagext.TagAdapter((javax.servlet.jsp.tagext.SimpleTag) _jsp_parent_tag));
        else
          _jsp_HasPermissionTag_15.setParent((javax.servlet.jsp.tagext.Tag) null);
        _jsp_HasPermissionTag_15.setName("user:create");
      }

      return _jsp_HasPermissionTag_15;
    }
    private org.apache.shiro.web.tags.PrincipalTag _jsp_PrincipalTag_16;

    final org.apache.shiro.web.tags.PrincipalTag get_jsp_PrincipalTag_16(PageContext pageContext, javax.servlet.jsp.tagext.JspTag _jsp_parent_tag) throws Throwable
    {
      if (_jsp_PrincipalTag_16 == null) {
        _jsp_PrincipalTag_16 = new org.apache.shiro.web.tags.PrincipalTag();
        _jsp_PrincipalTag_16.setPageContext(pageContext);
        _jsp_PrincipalTag_16.setParent((javax.servlet.jsp.tagext.Tag) _jsp_HasPermissionTag_15);
      }

      return _jsp_PrincipalTag_16;
    }
    private org.apache.shiro.web.tags.LacksPermissionTag _jsp_LacksPermissionTag_17;

    final org.apache.shiro.web.tags.LacksPermissionTag get_jsp_LacksPermissionTag_17(PageContext pageContext, javax.servlet.jsp.tagext.JspTag _jsp_parent_tag) throws Throwable
    {
      if (_jsp_LacksPermissionTag_17 == null) {
        _jsp_LacksPermissionTag_17 = new org.apache.shiro.web.tags.LacksPermissionTag();
        _jsp_LacksPermissionTag_17.setPageContext(pageContext);
        if (_jsp_parent_tag instanceof javax.servlet.jsp.tagext.Tag)
          _jsp_LacksPermissionTag_17.setParent((javax.servlet.jsp.tagext.Tag) _jsp_parent_tag);
        else if (_jsp_parent_tag instanceof javax.servlet.jsp.tagext.SimpleTag)
          _jsp_LacksPermissionTag_17.setParent(new javax.servlet.jsp.tagext.TagAdapter((javax.servlet.jsp.tagext.SimpleTag) _jsp_parent_tag));
        else
          _jsp_LacksPermissionTag_17.setParent((javax.servlet.jsp.tagext.Tag) null);
        _jsp_LacksPermissionTag_17.setName("org:create");
      }

      return _jsp_LacksPermissionTag_17;
    }
    private org.apache.shiro.web.tags.PrincipalTag _jsp_PrincipalTag_18;

    final org.apache.shiro.web.tags.PrincipalTag get_jsp_PrincipalTag_18(PageContext pageContext, javax.servlet.jsp.tagext.JspTag _jsp_parent_tag) throws Throwable
    {
      if (_jsp_PrincipalTag_18 == null) {
        _jsp_PrincipalTag_18 = new org.apache.shiro.web.tags.PrincipalTag();
        _jsp_PrincipalTag_18.setPageContext(pageContext);
        _jsp_PrincipalTag_18.setParent((javax.servlet.jsp.tagext.Tag) _jsp_LacksPermissionTag_17);
      }

      return _jsp_PrincipalTag_18;
    }
    private org.apache.shiro.web.tags.PrincipalTag _jsp_PrincipalTag_86;

    final org.apache.shiro.web.tags.PrincipalTag get_jsp_PrincipalTag_86(PageContext pageContext, javax.servlet.jsp.tagext.JspTag _jsp_parent_tag) throws Throwable
    {
      if (_jsp_PrincipalTag_86 == null) {
        _jsp_PrincipalTag_86 = new org.apache.shiro.web.tags.PrincipalTag();
        _jsp_PrincipalTag_86.setPageContext(pageContext);
        _jsp_PrincipalTag_86.setParent((javax.servlet.jsp.tagext.Tag) _jsp_parent_tag);
      }

      return _jsp_PrincipalTag_86;
    }
    private org.apache.shiro.web.tags.PrincipalTag _jsp_PrincipalTag_91;

    final org.apache.shiro.web.tags.PrincipalTag get_jsp_PrincipalTag_91(PageContext pageContext, javax.servlet.jsp.tagext.JspTag _jsp_parent_tag) throws Throwable
    {
      if (_jsp_PrincipalTag_91 == null) {
        _jsp_PrincipalTag_91 = new org.apache.shiro.web.tags.PrincipalTag();
        _jsp_PrincipalTag_91.setPageContext(pageContext);
        _jsp_PrincipalTag_91.setParent((javax.servlet.jsp.tagext.Tag) _jsp_parent_tag);
      }

      return _jsp_PrincipalTag_91;
    }
    private org.apache.shiro.web.tags.PrincipalTag _jsp_PrincipalTag_96;

    final org.apache.shiro.web.tags.PrincipalTag get_jsp_PrincipalTag_96(PageContext pageContext, javax.servlet.jsp.tagext.JspTag _jsp_parent_tag) throws Throwable
    {
      if (_jsp_PrincipalTag_96 == null) {
        _jsp_PrincipalTag_96 = new org.apache.shiro.web.tags.PrincipalTag();
        _jsp_PrincipalTag_96.setPageContext(pageContext);
        _jsp_PrincipalTag_96.setParent((javax.servlet.jsp.tagext.Tag) _jsp_parent_tag);
      }

      return _jsp_PrincipalTag_96;
    }

    void release()
    {
      if (_jsp_GuestTag_3 != null)
        _jsp_GuestTag_3.release();
      if (_jsp_UserTag_4 != null)
        _jsp_UserTag_4.release();
      if (_jsp_PrincipalTag_5 != null)
        _jsp_PrincipalTag_5.release();
      if (_jsp_AuthenticatedTag_6 != null)
        _jsp_AuthenticatedTag_6.release();
      if (_jsp_PrincipalTag_7 != null)
        _jsp_PrincipalTag_7.release();
      if (_jsp_NotAuthenticatedTag_8 != null)
        _jsp_NotAuthenticatedTag_8.release();
      if (_jsp_HasRoleTag_9 != null)
        _jsp_HasRoleTag_9.release();
      if (_jsp_PrincipalTag_10 != null)
        _jsp_PrincipalTag_10.release();
      if (_jsp_HasAnyRolesTag_11 != null)
        _jsp_HasAnyRolesTag_11.release();
      if (_jsp_PrincipalTag_12 != null)
        _jsp_PrincipalTag_12.release();
      if (_jsp_LacksRoleTag_13 != null)
        _jsp_LacksRoleTag_13.release();
      if (_jsp_PrincipalTag_14 != null)
        _jsp_PrincipalTag_14.release();
      if (_jsp_HasPermissionTag_15 != null)
        _jsp_HasPermissionTag_15.release();
      if (_jsp_PrincipalTag_16 != null)
        _jsp_PrincipalTag_16.release();
      if (_jsp_LacksPermissionTag_17 != null)
        _jsp_LacksPermissionTag_17.release();
      if (_jsp_PrincipalTag_18 != null)
        _jsp_PrincipalTag_18.release();
      if (_jsp_PrincipalTag_86 != null)
        _jsp_PrincipalTag_86.release();
      if (_jsp_PrincipalTag_91 != null)
        _jsp_PrincipalTag_91.release();
      if (_jsp_PrincipalTag_96 != null)
        _jsp_PrincipalTag_96.release();
    }
  }

  public java.util.HashMap<String,java.lang.reflect.Method> _caucho_getFunctionMap()
  {
    return _jsp_functionMap;
  }

  public void caucho_init(ServletConfig config)
  {
    try {
      com.caucho.server.webapp.WebApp webApp
        = (com.caucho.server.webapp.WebApp) config.getServletContext();
      init(config);
      if (com.caucho.jsp.JspManager.getCheckInterval() >= 0)
        _caucho_depends.setCheckInterval(com.caucho.jsp.JspManager.getCheckInterval());
      _jsp_pageManager = webApp.getJspApplicationContext().getPageManager();
      com.caucho.jsp.TaglibManager manager = webApp.getJspApplicationContext().getTaglibManager();
      manager.addTaglibFunctions(_jsp_functionMap, "shiro", "http://shiro.apache.org/tags");
      com.caucho.jsp.PageContextImpl pageContext = new com.caucho.jsp.InitPageContextImpl(webApp, this);
      _caucho_expr_0 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${pageContext.request.contextPath}");
      new _jsp._web_22dinf._tags._hasallroles__tag().caucho_init(config);
      new _jsp._web_22dinf._tags._hasallpermissions__tag().caucho_init(config);
      new _jsp._web_22dinf._tags._hasanypermissions__tag().caucho_init(config);
    } catch (Exception e) {
      throw com.caucho.config.ConfigException.create(e);
    }
  }
  private static com.caucho.el.Expr _caucho_expr_0;

  private final static char []_jsp_string22;
  private final static char []_jsp_string3;
  private final static char []_jsp_string17;
  private final static char []_jsp_string16;
  private final static char []_jsp_string6;
  private final static char []_jsp_string7;
  private final static char []_jsp_string10;
  private final static char []_jsp_string9;
  private final static char []_jsp_string0;
  private final static char []_jsp_string15;
  private final static char []_jsp_string8;
  private final static char []_jsp_string19;
  private final static char []_jsp_string1;
  private final static char []_jsp_string25;
  private final static char []_jsp_string2;
  private final static char []_jsp_string12;
  private final static char []_jsp_string20;
  private final static char []_jsp_string18;
  private final static char []_jsp_string11;
  private final static char []_jsp_string21;
  private final static char []_jsp_string4;
  private final static char []_jsp_string24;
  private final static char []_jsp_string5;
  private final static char []_jsp_string23;
  private final static char []_jsp_string13;
  private final static char []_jsp_string14;
  static {
    _jsp_string22 = "\n\n</body>\n</html>".toCharArray();
    _jsp_string3 = "\n\n<!-- \u7528\u6237\u5df2\u7ecf\u8eab\u4efd\u9a8c\u8bc1/\u8bb0\u4f4f\u6211\u767b\u5f55\u540e\u663e\u793a\u76f8\u5e94\u7684\u4fe1\u606f\u3002 -->\n".toCharArray();
    _jsp_string17 = "]\u6ca1\u6709\u89d2\u8272abc<br/>\n".toCharArray();
    _jsp_string16 = "\n\n<!-- \u5982\u679c\u5f53\u524dSubject\u6ca1\u6709\u89d2\u8272\u5c06\u663e\u793abody\u4f53\u5185\u5bb9\u3002  -->\n".toCharArray();
    _jsp_string6 = "/logout\">\u70b9\u51fb\u9000\u51fa</a><br/>\n".toCharArray();
    _jsp_string7 = "\n<!-- \u7528\u6237\u5df2\u7ecf\u8eab\u4efd\u9a8c\u8bc1\u901a\u8fc7\uff0c\u5373Subject.login\u767b\u5f55\u6210\u529f\uff0c\u4e0d\u662f\u8bb0\u4f4f\u6211\u767b\u5f55\u7684\u3002  -->\n".toCharArray();
    _jsp_string10 = "\n\n<!-- \u7528\u6237\u5df2\u7ecf\u8eab\u4efd\u9a8c\u8bc1\u901a\u8fc7\uff0c\u5373\u6ca1\u6709\u8c03\u7528Subject.login\u8fdb\u884c\u767b\u5f55\uff0c\u5305\u62ec\u8bb0\u4f4f\u6211\u81ea\u52a8\u767b\u5f55\u7684\u4e5f\u5c5e\u4e8e\u672a\u8fdb\u884c\u8eab\u4efd\u9a8c\u8bc1\u3002 -->\n".toCharArray();
    _jsp_string9 = "]\u5df2\u8eab\u4efd\u9a8c\u8bc1\u901a\u8fc7<br/>\n".toCharArray();
    _jsp_string0 = "\n\n\n<html>\n<body>\n<!-- \u7528\u6237\u6ca1\u6709\u8eab\u4efd\u9a8c\u8bc1\u65f6\u663e\u793a\u76f8\u5e94\u4fe1\u606f\uff0c\u5373\u6e38\u5ba2\u8bbf\u95ee\u4fe1\u606f\u3002 -->\n".toCharArray();
    _jsp_string15 = "]\u62e5\u6709\u89d2\u8272admin\u6216user<br/>\n".toCharArray();
    _jsp_string8 = "\n    \u7528\u6237[".toCharArray();
    _jsp_string19 = "]\u62e5\u6709\u6743\u9650user:create<br/>\n".toCharArray();
    _jsp_string1 = "\n    \u6b22\u8fce\u6e38\u5ba2\u8bbf\u95ee\uff0c<a href=\"".toCharArray();
    _jsp_string25 = "]\u62e5\u6709\u6743\u9650user:create\u6216abc:update<br/>\n".toCharArray();
    _jsp_string2 = "/login.jsp\">\u70b9\u51fb\u767b\u5f55</a><br/>\n".toCharArray();
    _jsp_string12 = "\n\n<!-- \u5982\u679c\u5f53\u524dSubject\u6709\u89d2\u8272\u5c06\u663e\u793abody\u4f53\u5185\u5bb9\u3002 -->\n".toCharArray();
    _jsp_string20 = "\n\n".toCharArray();
    _jsp_string18 = "\n\n<!-- \u5982\u679c\u5f53\u524dSubject\u6ca1\u6709\u6743\u9650\u5c06\u663e\u793abody\u4f53\u5185\u5bb9\u3002 -->\n".toCharArray();
    _jsp_string11 = "\n    \u672a\u8eab\u4efd\u9a8c\u8bc1\uff08\u5305\u62ec\u8bb0\u4f4f\u6211\uff09<br/>\n".toCharArray();
    _jsp_string21 = "]\u6ca1\u6709\u6743\u9650org:create<br/>\n".toCharArray();
    _jsp_string4 = "\n    \u6b22\u8fce[".toCharArray();
    _jsp_string24 = "]\u62e5\u6709\u6743\u9650user:create\u548cuser:update<br/>\n".toCharArray();
    _jsp_string5 = "]\u767b\u5f55\uff0c<a href=\"".toCharArray();
    _jsp_string23 = "]\u62e5\u6709\u89d2\u8272admin\u548cuser<br/>\n".toCharArray();
    _jsp_string13 = "]\u62e5\u6709\u89d2\u8272admin<br/>\n".toCharArray();
    _jsp_string14 = "\n\n<!-- \u5982\u679c\u5f53\u524dSubject\u6709\u4efb\u610f\u4e00\u4e2a\u89d2\u8272\uff08\u6216\u7684\u5173\u7cfb\uff09\u5c06\u663e\u793abody\u4f53\u5185\u5bb9 -->\n".toCharArray();
  }
}
