/*
 * JSP generated by Resin Professional 4.0.13 (built Tue, 09 Nov 2010 03:50:16 PST)
 */

package _jsp._web_22dinf._jsp;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;

public class _index__jsp extends com.caucho.jsp.JavaPage
{
  private static final java.util.HashMap<String,java.lang.reflect.Method> _jsp_functionMap = new java.util.HashMap<String,java.lang.reflect.Method>();
  private boolean _caucho_isDead;
  private boolean _caucho_isNotModified;
  private com.caucho.jsp.PageManager _jsp_pageManager;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.WebApp _jsp_application = _caucho_getApplication();
    com.caucho.jsp.PageContextImpl pageContext = _jsp_pageManager.allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true, false);

    TagState _jsp_state = new TagState();

    try {
      _jspService(request, response, pageContext, _jsp_application, session, _jsp_state);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      _jsp_state.release();
      _jsp_pageManager.freePageContext(pageContext);
    }
  }
  
  private void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response,
              com.caucho.jsp.PageContextImpl pageContext,
              javax.servlet.ServletContext application,
              javax.servlet.http.HttpSession session,
              TagState _jsp_state)
    throws Throwable
  {
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    final javax.el.ELContext _jsp_env = pageContext.getELContext();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    javax.servlet.jsp.tagext.JspTag _jsp_parent_tag = null;
    com.caucho.jsp.PageContextImpl _jsp_parentContext = pageContext;
    response.setContentType("text/html;charset=UTF-8");
    String _caucho_request_character_encoding = request.getCharacterEncoding();
    if (_caucho_request_character_encoding == null || "".equals(_caucho_request_character_encoding))
      request.setCharacterEncoding("utf-8");
    org.apache.shiro.web.tags.PrincipalTag _jsp_PrincipalTag_0 = null;
    com.caucho.jsp.IteratorLoopSupportTag _jsp_loop_2 = null;

    out.write(_jsp_string0, 0, _jsp_string0.length);
    _caucho_expr_0.print(out, _jsp_env, false);
    out.write(_jsp_string1, 0, _jsp_string1.length);
    _caucho_expr_0.print(out, _jsp_env, false);
    out.write(_jsp_string2, 0, _jsp_string2.length);
    _jsp_PrincipalTag_0 = _jsp_state.get_jsp_PrincipalTag_0(pageContext, _jsp_parent_tag);
    _jsp_PrincipalTag_0.doStartTag();
    out.write(_jsp_string3, 0, _jsp_string3.length);
    _caucho_expr_0.print(out, _jsp_env, false);
    out.write(_jsp_string4, 0, _jsp_string4.length);
    _jsp_loop_2 = _jsp_state.get_jsp_loop_2(pageContext, _jsp_parent_tag);
    java.lang.Object _jsp_items_7 = _caucho_expr_1.evalObject(_jsp_env);
    java.util.Iterator _jsp_iter_7 = com.caucho.jstl.rt.CoreForEachTag.getIterator(_jsp_items_7);
    _jsp_loop_2.init(0, Integer.MAX_VALUE, 1, false, false, false);
    while (_jsp_iter_7.hasNext()) {
      Object _jsp_i_7 = _jsp_iter_7.next();
      _jsp_loop_2.setCurrent(_jsp_i_7, _jsp_iter_7.hasNext());
      pageContext.setAttribute("m", _jsp_i_7);
      out.write(_jsp_string5, 0, _jsp_string5.length);
      _caucho_expr_0.print(out, _jsp_env, false);
      _caucho_expr_2.print(out, _jsp_env, false);
      out.write(_jsp_string6, 0, _jsp_string6.length);
      _caucho_expr_3.print(out, _jsp_env, false);
      out.write(_jsp_string7, 0, _jsp_string7.length);
    }
    pageContext.pageSetOrRemove("m", null);
    out.write(_jsp_string8, 0, _jsp_string8.length);
    _caucho_expr_0.print(out, _jsp_env, false);
    out.write(_jsp_string9, 0, _jsp_string9.length);
    _caucho_expr_0.print(out, _jsp_env, false);
    out.write(_jsp_string10, 0, _jsp_string10.length);
  }

  private com.caucho.make.DependencyContainer _caucho_depends
    = new com.caucho.make.DependencyContainer();

  public java.util.ArrayList<com.caucho.vfs.Dependency> _caucho_getDependList()
  {
    return _caucho_depends.getDependencies();
  }

  public void _caucho_addDepend(com.caucho.vfs.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    _caucho_depends.add(depend);
  }

  protected void _caucho_setNeverModified(boolean isNotModified)
  {
    _caucho_isNotModified = true;
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;

    if (_caucho_isNotModified)
      return false;

    if (com.caucho.server.util.CauchoSystem.getVersionId() != 72739197937975180L)
      return true;

    return _caucho_depends.isModified();
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
    TagState tagState;
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.server.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("WEB-INF/jsp/index.jsp"), -8114630060054313078L, false);
    _caucho_depends.add(depend);
    depend = new com.caucho.vfs.Depend(mergePath.lookup("jar:file:/E:/Workspaces/shiro-example/shiro-example-chapter16/target/shiro-example-chapter16/WEB-INF/lib/shiro-web-1.2.2.jar!/META-INF/shiro.tld"), -6207406093825368018L, false);
    _caucho_depends.add(depend);
    _caucho_depends.add(new com.caucho.make.ClassDependency("org.apache.shiro.web.tags.PrincipalTag", -4653556525534072090L));
  }

  static {
    try {
    } catch (Exception e) {
      e.printStackTrace();
      throw new RuntimeException(e);
    }
  }

  final static class TagState {
    private org.apache.shiro.web.tags.PrincipalTag _jsp_PrincipalTag_0;

    final org.apache.shiro.web.tags.PrincipalTag get_jsp_PrincipalTag_0(PageContext pageContext, javax.servlet.jsp.tagext.JspTag _jsp_parent_tag) throws Throwable
    {
      if (_jsp_PrincipalTag_0 == null) {
        _jsp_PrincipalTag_0 = new org.apache.shiro.web.tags.PrincipalTag();
        _jsp_PrincipalTag_0.setPageContext(pageContext);
        if (_jsp_parent_tag instanceof javax.servlet.jsp.tagext.Tag)
          _jsp_PrincipalTag_0.setParent((javax.servlet.jsp.tagext.Tag) _jsp_parent_tag);
        else if (_jsp_parent_tag instanceof javax.servlet.jsp.tagext.SimpleTag)
          _jsp_PrincipalTag_0.setParent(new javax.servlet.jsp.tagext.TagAdapter((javax.servlet.jsp.tagext.SimpleTag) _jsp_parent_tag));
        else
          _jsp_PrincipalTag_0.setParent((javax.servlet.jsp.tagext.Tag) null);
      }

      return _jsp_PrincipalTag_0;
    }
    private com.caucho.jsp.IteratorLoopSupportTag _jsp_loop_2;

    final com.caucho.jsp.IteratorLoopSupportTag get_jsp_loop_2(PageContext pageContext, javax.servlet.jsp.tagext.JspTag _jsp_parent_tag) throws Throwable
    {
      if (_jsp_loop_2 == null) {
        _jsp_loop_2 = new com.caucho.jsp.IteratorLoopSupportTag();
        _jsp_loop_2.setParent((javax.servlet.jsp.tagext.Tag) null);
      }

      return _jsp_loop_2;
    }

    void release()
    {
      if (_jsp_PrincipalTag_0 != null)
        _jsp_PrincipalTag_0.release();
    }
  }

  public java.util.HashMap<String,java.lang.reflect.Method> _caucho_getFunctionMap()
  {
    return _jsp_functionMap;
  }

  public void caucho_init(ServletConfig config)
  {
    try {
      com.caucho.server.webapp.WebApp webApp
        = (com.caucho.server.webapp.WebApp) config.getServletContext();
      init(config);
      if (com.caucho.jsp.JspManager.getCheckInterval() >= 0)
        _caucho_depends.setCheckInterval(com.caucho.jsp.JspManager.getCheckInterval());
      _jsp_pageManager = webApp.getJspApplicationContext().getPageManager();
      com.caucho.jsp.TaglibManager manager = webApp.getJspApplicationContext().getTaglibManager();
      manager.addTaglibFunctions(_jsp_functionMap, "c", "http://java.sun.com/jsp/jstl/core");
      manager.addTaglibFunctions(_jsp_functionMap, "shiro", "http://shiro.apache.org/tags");
      com.caucho.jsp.PageContextImpl pageContext = new com.caucho.jsp.InitPageContextImpl(webApp, this);
      _caucho_expr_0 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${pageContext.request.contextPath}");
      _caucho_expr_1 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${menus}");
      _caucho_expr_2 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${m.url}");
      _caucho_expr_3 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${m.name}");
    } catch (Exception e) {
      throw com.caucho.config.ConfigException.create(e);
    }
  }
  private static com.caucho.el.Expr _caucho_expr_0;
  private static com.caucho.el.Expr _caucho_expr_1;
  private static com.caucho.el.Expr _caucho_expr_2;
  private static com.caucho.el.Expr _caucho_expr_3;

  private final static char []_jsp_string6;
  private final static char []_jsp_string5;
  private final static char []_jsp_string7;
  private final static char []_jsp_string3;
  private final static char []_jsp_string9;
  private final static char []_jsp_string0;
  private final static char []_jsp_string8;
  private final static char []_jsp_string4;
  private final static char []_jsp_string10;
  private final static char []_jsp_string2;
  private final static char []_jsp_string1;
  static {
    _jsp_string6 = "\" target=\"content\">".toCharArray();
    _jsp_string5 = "\n        <a href=\"".toCharArray();
    _jsp_string7 = "</a><br/>\n    ".toCharArray();
    _jsp_string3 = "]\u5b66\u4e60Shiro\u7efc\u5408\u6848\u4f8b\uff0c<a href=\"".toCharArray();
    _jsp_string9 = "/static/js/jquery-1.11.0.min.js\"></script>\n<script src=\"".toCharArray();
    _jsp_string0 = "\n\n\n\n<html>\n<head>\n    <title>Shiro\u7efc\u5408\u6848\u4f8b</title>\n    <link rel=\"stylesheet\" href=\"".toCharArray();
    _jsp_string8 = "\n</div>\n\n\n<script src=\"".toCharArray();
    _jsp_string4 = "/logout\">\u9000\u51fa</a></div>\n<div class=\"ui-layout-south\">\n    \u83b7\u53d6\u6e90\u7801\uff1a<a href=\"https://github.com/zhangkaitao/shiro-example\" target=\"_blank\">https://github.com/zhangkaitao/shiro-example</a>\n</div>\n<div class=\"ui-layout-west\">\n    \u529f\u80fd\u83dc\u5355<br/>\n    ".toCharArray();
    _jsp_string10 = "/static/js/jquery.layout-latest.min.js\"></script>\n<script>\n    $(function () {\n        $(document).ready(function () {\n            $('body').layout({ applyDemoStyles: true });\n        });\n    });\n</script>\n</body>\n</html>\n".toCharArray();
    _jsp_string2 = "/welcome\" frameborder=\"0\" scrolling=\"auto\"></iframe>\n<div class=\"ui-layout-north\">\u6b22\u8fce[".toCharArray();
    _jsp_string1 = "/static/css/layout-default-latest.css\">\n</head>\n<body>\n\n<iframe name=\"content\" class=\"ui-layout-center\"\n        src=\"".toCharArray();
  }
}
