/*
 * JSP generated by Resin Professional 4.0.13 (built Tue, 09 Nov 2010 03:50:16 PST)
 */

package _jsp;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;
import org.apache.shiro.SecurityUtils;
import com.github.shiro.session.mgt.OnlineSession;
import com.github.shiro.session.dao.MySessionDAO;
import java.io.Serializable;

public class _index__jsp extends com.caucho.jsp.JavaPage
{
  private static final java.util.HashMap<String,java.lang.reflect.Method> _jsp_functionMap = new java.util.HashMap<String,java.lang.reflect.Method>();
  private boolean _caucho_isDead;
  private boolean _caucho_isNotModified;
  private com.caucho.jsp.PageManager _jsp_pageManager;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.WebApp _jsp_application = _caucho_getApplication();
    com.caucho.jsp.PageContextImpl pageContext = _jsp_pageManager.allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true, false);

    TagState _jsp_state = new TagState();

    try {
      _jspService(request, response, pageContext, _jsp_application, session, _jsp_state);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      _jsp_state.release();
      _jsp_pageManager.freePageContext(pageContext);
    }
  }
  
  private void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response,
              com.caucho.jsp.PageContextImpl pageContext,
              javax.servlet.ServletContext application,
              javax.servlet.http.HttpSession session,
              TagState _jsp_state)
    throws Throwable
  {
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    final javax.el.ELContext _jsp_env = pageContext.getELContext();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    javax.servlet.jsp.tagext.JspTag _jsp_parent_tag = null;
    com.caucho.jsp.PageContextImpl _jsp_parentContext = pageContext;
    response.setContentType("text/html;charset=UTF-8");
    String _caucho_request_character_encoding = request.getCharacterEncoding();
    if (_caucho_request_character_encoding == null || "".equals(_caucho_request_character_encoding))
      request.setCharacterEncoding("utf-8");
    org.apache.shiro.web.tags.GuestTag _jsp_GuestTag_0 = null;
    org.apache.shiro.web.tags.UserTag _jsp_UserTag_1 = null;
    org.apache.shiro.web.tags.PrincipalTag _jsp_PrincipalTag_2 = null;

    out.write(_jsp_string0, 0, _jsp_string0.length);
    _jsp_GuestTag_0 = _jsp_state.get_jsp_GuestTag_0(pageContext, _jsp_parent_tag);
    int _jspEval5 = _jsp_GuestTag_0.doStartTag();
    if (_jspEval5 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      out.write(_jsp_string1, 0, _jsp_string1.length);
      _caucho_expr_0.print(out, _jsp_env, false);
      out.write(_jsp_string2, 0, _jsp_string2.length);
    }
    out.write('\n');
    _jsp_UserTag_1 = _jsp_state.get_jsp_UserTag_1(pageContext, _jsp_parent_tag);
    int _jspEval9 = _jsp_UserTag_1.doStartTag();
    if (_jspEval9 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      out.write(_jsp_string3, 0, _jsp_string3.length);
      _jsp_PrincipalTag_2 = _jsp_state.get_jsp_PrincipalTag_2(pageContext, _jsp_parent_tag);
      _jsp_PrincipalTag_2.doStartTag();
      out.write(_jsp_string4, 0, _jsp_string4.length);
      _caucho_expr_0.print(out, _jsp_env, false);
      out.write(_jsp_string5, 0, _jsp_string5.length);
    }
    out.write(_jsp_string6, 0, _jsp_string6.length);
    int _jspEval17 = _jsp_UserTag_1.doStartTag();
    if (_jspEval17 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      out.write(_jsp_string7, 0, _jsp_string7.length);
      
        SecurityUtils.getSubject().getSession().setAttribute("key", 123);
        out.print(SecurityUtils.getSubject().getSession().getAttribute("key"));
    
      out.write(_jsp_string8, 0, _jsp_string8.length);
      
        MySessionDAO sessionDAO = new MySessionDAO();
        Serializable sessionId = SecurityUtils.getSubject().getSession().getId();
        OnlineSession onlineSession = (OnlineSession)sessionDAO.readSession(sessionId);
        out.print(onlineSession.getStatus().getInfo());
    
      out.write('\n');
    }
    out.write(_jsp_string9, 0, _jsp_string9.length);
  }

  private com.caucho.make.DependencyContainer _caucho_depends
    = new com.caucho.make.DependencyContainer();

  public java.util.ArrayList<com.caucho.vfs.Dependency> _caucho_getDependList()
  {
    return _caucho_depends.getDependencies();
  }

  public void _caucho_addDepend(com.caucho.vfs.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    _caucho_depends.add(depend);
  }

  protected void _caucho_setNeverModified(boolean isNotModified)
  {
    _caucho_isNotModified = true;
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;

    if (_caucho_isNotModified)
      return false;

    if (com.caucho.server.util.CauchoSystem.getVersionId() != 72739197937975180L)
      return true;

    return _caucho_depends.isModified();
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
    TagState tagState;
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.server.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("index.jsp"), -3678759089854863909L, false);
    _caucho_depends.add(depend);
    depend = new com.caucho.vfs.Depend(mergePath.lookup("jar:file:/E:/Workspaces/shiro-example/shiro-example-chapter10/target/shiro-example-chapter10/WEB-INF/lib/shiro-web-1.2.2.jar!/META-INF/shiro.tld"), -6207406093825368018L, false);
    _caucho_depends.add(depend);
    _caucho_depends.add(new com.caucho.make.ClassDependency("org.apache.shiro.web.tags.GuestTag", 5701916638987586964L));
    _caucho_depends.add(new com.caucho.make.ClassDependency("org.apache.shiro.web.tags.PrincipalTag", -4653556525534072090L));
    _caucho_depends.add(new com.caucho.make.ClassDependency("org.apache.shiro.web.tags.UserTag", 6694308417190239424L));
  }

  static {
    try {
    } catch (Exception e) {
      e.printStackTrace();
      throw new RuntimeException(e);
    }
  }

  final static class TagState {
    private org.apache.shiro.web.tags.GuestTag _jsp_GuestTag_0;

    final org.apache.shiro.web.tags.GuestTag get_jsp_GuestTag_0(PageContext pageContext, javax.servlet.jsp.tagext.JspTag _jsp_parent_tag) throws Throwable
    {
      if (_jsp_GuestTag_0 == null) {
        _jsp_GuestTag_0 = new org.apache.shiro.web.tags.GuestTag();
        _jsp_GuestTag_0.setPageContext(pageContext);
        if (_jsp_parent_tag instanceof javax.servlet.jsp.tagext.Tag)
          _jsp_GuestTag_0.setParent((javax.servlet.jsp.tagext.Tag) _jsp_parent_tag);
        else if (_jsp_parent_tag instanceof javax.servlet.jsp.tagext.SimpleTag)
          _jsp_GuestTag_0.setParent(new javax.servlet.jsp.tagext.TagAdapter((javax.servlet.jsp.tagext.SimpleTag) _jsp_parent_tag));
        else
          _jsp_GuestTag_0.setParent((javax.servlet.jsp.tagext.Tag) null);
      }

      return _jsp_GuestTag_0;
    }
    private org.apache.shiro.web.tags.UserTag _jsp_UserTag_1;

    final org.apache.shiro.web.tags.UserTag get_jsp_UserTag_1(PageContext pageContext, javax.servlet.jsp.tagext.JspTag _jsp_parent_tag) throws Throwable
    {
      if (_jsp_UserTag_1 == null) {
        _jsp_UserTag_1 = new org.apache.shiro.web.tags.UserTag();
        _jsp_UserTag_1.setPageContext(pageContext);
        if (_jsp_parent_tag instanceof javax.servlet.jsp.tagext.Tag)
          _jsp_UserTag_1.setParent((javax.servlet.jsp.tagext.Tag) _jsp_parent_tag);
        else if (_jsp_parent_tag instanceof javax.servlet.jsp.tagext.SimpleTag)
          _jsp_UserTag_1.setParent(new javax.servlet.jsp.tagext.TagAdapter((javax.servlet.jsp.tagext.SimpleTag) _jsp_parent_tag));
        else
          _jsp_UserTag_1.setParent((javax.servlet.jsp.tagext.Tag) null);
      }

      return _jsp_UserTag_1;
    }
    private org.apache.shiro.web.tags.PrincipalTag _jsp_PrincipalTag_2;

    final org.apache.shiro.web.tags.PrincipalTag get_jsp_PrincipalTag_2(PageContext pageContext, javax.servlet.jsp.tagext.JspTag _jsp_parent_tag) throws Throwable
    {
      if (_jsp_PrincipalTag_2 == null) {
        _jsp_PrincipalTag_2 = new org.apache.shiro.web.tags.PrincipalTag();
        _jsp_PrincipalTag_2.setPageContext(pageContext);
        _jsp_PrincipalTag_2.setParent((javax.servlet.jsp.tagext.Tag) _jsp_UserTag_1);
      }

      return _jsp_PrincipalTag_2;
    }

    void release()
    {
      if (_jsp_GuestTag_0 != null)
        _jsp_GuestTag_0.release();
      if (_jsp_UserTag_1 != null)
        _jsp_UserTag_1.release();
      if (_jsp_PrincipalTag_2 != null)
        _jsp_PrincipalTag_2.release();
    }
  }

  public java.util.HashMap<String,java.lang.reflect.Method> _caucho_getFunctionMap()
  {
    return _jsp_functionMap;
  }

  public void caucho_init(ServletConfig config)
  {
    try {
      com.caucho.server.webapp.WebApp webApp
        = (com.caucho.server.webapp.WebApp) config.getServletContext();
      init(config);
      if (com.caucho.jsp.JspManager.getCheckInterval() >= 0)
        _caucho_depends.setCheckInterval(com.caucho.jsp.JspManager.getCheckInterval());
      _jsp_pageManager = webApp.getJspApplicationContext().getPageManager();
      com.caucho.jsp.TaglibManager manager = webApp.getJspApplicationContext().getTaglibManager();
      manager.addTaglibFunctions(_jsp_functionMap, "shiro", "http://shiro.apache.org/tags");
      com.caucho.jsp.PageContextImpl pageContext = new com.caucho.jsp.InitPageContextImpl(webApp, this);
      _caucho_expr_0 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${pageContext.request.contextPath}");
    } catch (Exception e) {
      throw com.caucho.config.ConfigException.create(e);
    }
  }
  private static com.caucho.el.Expr _caucho_expr_0;

  private final static char []_jsp_string9;
  private final static char []_jsp_string5;
  private final static char []_jsp_string0;
  private final static char []_jsp_string1;
  private final static char []_jsp_string7;
  private final static char []_jsp_string2;
  private final static char []_jsp_string6;
  private final static char []_jsp_string3;
  private final static char []_jsp_string4;
  private final static char []_jsp_string8;
  static {
    _jsp_string9 = "\n\n</body>".toCharArray();
    _jsp_string5 = "/logout\">\u70b9\u51fb\u9000\u51fa</a><br/>\n".toCharArray();
    _jsp_string0 = "\n\n\n\n\n\n<html>\n<body>\n".toCharArray();
    _jsp_string1 = "\n    \u6b22\u8fce\u6e38\u5ba2\u8bbf\u95ee\uff0c<a href=\"".toCharArray();
    _jsp_string7 = "\n    ".toCharArray();
    _jsp_string2 = "/login.jsp\">\u70b9\u51fb\u767b\u5f55</a><br/>\n".toCharArray();
    _jsp_string6 = "\n\n".toCharArray();
    _jsp_string3 = "\n    \u6b22\u8fce[".toCharArray();
    _jsp_string4 = "]\u767b\u5f55\uff0c<a href=\"".toCharArray();
    _jsp_string8 = "\n    <br/>\n    ".toCharArray();
  }
}
